name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SBT_OPTS: -Dlerna.enable.discipline

jobs:
  test:

    runs-on: ubuntu-latest

    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # https://github.com/actions/cache/blob/main/examples.md#scala---sbt
    - name: Cache sbt resources
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/coursier
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

    - name: Check code format
      run: sbt scalafmtCheckAll

    - name: Run tests
      run: sbt clean test

    - name: Run integration tests
      run: sh ./scripts/run-multijvm-test.sh 5
